### ISSUE TITLE
Can't connect to docker socket

### ISSUE THREAD

**Issue by BitWuehler** [SelfhostedPro/yacht-api#5]
Hey all together. Today I wanted to give yours new Version a try. Thanks for your work, i love your old work!

But if open the applications log I get this error:

``
yacht-alpha  | [ContainersService] [3/7/2024, 5:37:02 PM] Error getting containers: Cannot read properties of undefined (reading 'map')
``

My docker-compose look like that:

```
version: "3.3"
services:
  yacht-api:
    container_name: yacht-alpha
    restart: unless-stopped
    ports:
      - 3013:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/config
    image: ghcr.io/selfhostedpro/yacht-api:main
    healthcheck:
      test: curl --fail localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 70s
      timeout: 10s
    networks:
      caddy:
        ipv4_address: 192.168.112.21
        ipv6_address: 2001:ab12::21
networks:
  caddy:
    external: true

```

Do I have to use a volume or what do you think is the problem? My old yacht container runs with the same socket setttings and same host privileges.
